---
title: "AIRBNB en Manhattan"
date: "26/1/2021"
output:
  html_document: default
  word_document: default
---

```{r, warning=FALSE, include = FALSE}
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(rgeos)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
library(maps)
library(geosphere)
library(plotly)
library(ggthemes)
library(leaflet)
library(crosstalk)
```



```{r, include=FALSE, warning=FALSE}
setwd("/Applications/3ero/VIS/archive")
datos_mal = read.csv2("AB_NYC_2019.csv",encoding = "UTF-8")
datos_totales1 <- read.csv2("AB_NYC_2019.csv",encoding = "UTF-8", sep = ",")

datos_totales2 = subset(datos_totales1, datos_totales1$minimum_nights <= 30)

datos_totales = subset(datos_totales2, datos_totales2$price <= 1000)

datos_manhattan <- subset(datos_totales, datos_totales$neighbourhood_group == 'Manhattan')

datos_manhattan = datos_manhattan[(!datos_manhattan$room_type == "Shared room"),]



data <- as.data.frame(datos_manhattan)
```

```{r echo = FALSE}
colnames(datos_mal)
datos_mal[1:5,1]
```


```{r}
datos_totales1 <- read.csv2("AB_NYC_2019.csv",encoding = "UTF-8", sep = ",")
```

```{r echo=FALSE}
datos_totales1[1:10,c(1,3:7)]
```



```{r}
data$latitude <- as.numeric(as.character(data$latitude))

data$longitude <- as.numeric(as.character(data$longitude))

data$price <- as.numeric(data$price)

data$room_type <- factor(data$room_type)

```



```{r}
datos_totales2 = subset(datos_totales1, datos_totales1$minimum_nights <= 30)

datos_totales = subset(datos_totales2, datos_totales2$price <= 1000)

datos_manhattan <- subset(datos_totales, datos_totales$neighbourhood_group == 'Manhattan')


data <- as.data.frame(datos_manhattan)
```

```{r echo=FALSE}
data$latitude <- as.numeric(as.character(data$latitude))

data$longitude <- as.numeric(as.character(data$longitude))

data$price <- as.numeric(data$price)

data$room_type <- factor(data$room_type)

```


```{r echo = FALSE}
sum(data$room_type == "Shared room")
```


```{r}
sum(data$room_type == "Private room")
```


```{r}
sum(data$room_type == "Entire home/apt")
```


```{r echo = FALSE}
data$room_type = as.factor(data$room_type)
ggplot(data=data, aes(x= room_type)) + 
    geom_bar(stat="count", fill = "#FA8072")+ ylab("Número de alojamientos") +  xlab("Tipo de alojamiento")
```



```{r}
data = data[(!data$room_type == "Shared room"),]
```



```{r include = FALSE}
#1
data$Zonas_agregadas[data$neighbourhood == "Inwood"] <- "Washington Heights - Inwood"
data$Zonas_agregadas[data$neighbourhood == "Washington Heights"] <- "Washington Heights - Inwood"
data$Zonas_agregadas[data$neighbourhood == "Marble Hill"] <- "Washington Heights - Inwood"


#2
data$Zonas_agregadas[data$neighbourhood == "Morningside Heights"] <- "Central Harlem - Morningside Heights"
data$Zonas_agregadas[data$neighbourhood == "Harlem"] <- "Central Harlem - Morningside Heights"


#3
data$Zonas_agregadas[data$neighbourhood == "East Harlem"] <- "East Harlem"


#4
data$Zonas_agregadas[data$neighbourhood == "Upper West Side"] <- "Upper West Side"


#5
data$Zonas_agregadas[data$neighbourhood == "Roosevelt Island"] <- "Upper East Side"
data$Zonas_agregadas[data$neighbourhood == "Upper East Side"] <- "Upper East Side"


#6
data$Zonas_agregadas[data$neighbourhood == "Midtown"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Chelsea"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Hell's Kitchen"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "NoHo"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Theater District"] <- "Chelsea - Clinton"


#7
data$Zonas_agregadas[data$neighbourhood == "Gramercy"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Kips Bay"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Little Italy"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Murray Hill"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Nolita"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Stuyvesant Town"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Flatiron District"] <- "Gramercy Park -  Murray Hill"



#8
data$Zonas_agregadas[data$neighbourhood == "Greenwich Village"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "SoHo"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "West Village"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "Chinatown"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "Civic Center"] <- "Greenwich Village - Soho"



#9
data$Zonas_agregadas[data$neighbourhood == "Lower East Side"] <- "Union Square - Lower East Side"
data$Zonas_agregadas[data$neighbourhood == "East Village"] <- "Union Square - Lower East Side"


#10
data$Zonas_agregadas[data$neighbourhood == "Tribeca"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Two Bridges"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Financial District"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Battery Park City"] <- "Lower Manhattan"
```


```{r echo = FALSE}
#Se vuelven a cargar los datos para asegurarnos que todo está correctamente

setwd("/Applications/3ero/VIS/archive")
datos_totales1 <- read.csv2("AB_NYC_2019.csv",encoding = "UTF-8", sep = ",")

datos_totales2 = subset(datos_totales1, datos_totales1$minimum_nights <= 30)

datos_totales = subset(datos_totales2, datos_totales2$price <= 1000)

datos_manhattan <- subset(datos_totales, datos_totales$neighbourhood_group == 'Manhattan')

datos_manhattan = datos_manhattan[(!datos_manhattan$room_type == "Shared room"),]



data <- as.data.frame(datos_manhattan)



#1
data$Zonas_agregadas[data$neighbourhood == "Inwood"] <- "Washington Heights - Inwood"
data$Zonas_agregadas[data$neighbourhood == "Washington Heights"] <- "Washington Heights - Inwood"
data$Zonas_agregadas[data$neighbourhood == "Marble Hill"] <- "Washington Heights - Inwood"


#2
data$Zonas_agregadas[data$neighbourhood == "Morningside Heights"] <- "Central Harlem - Morningside Heights"
data$Zonas_agregadas[data$neighbourhood == "Harlem"] <- "Central Harlem - Morningside Heights"


#3
data$Zonas_agregadas[data$neighbourhood == "East Harlem"] <- "East Harlem"


#4
data$Zonas_agregadas[data$neighbourhood == "Upper West Side"] <- "Upper West Side"


#5
data$Zonas_agregadas[data$neighbourhood == "Roosevelt Island"] <- "Upper East Side"
data$Zonas_agregadas[data$neighbourhood == "Upper East Side"] <- "Upper East Side"


#6
data$Zonas_agregadas[data$neighbourhood == "Midtown"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Chelsea"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Hell's Kitchen"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "NoHo"] <- "Chelsea - Clinton"
data$Zonas_agregadas[data$neighbourhood == "Theater District"] <- "Chelsea - Clinton"


#7
data$Zonas_agregadas[data$neighbourhood == "Gramercy"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Kips Bay"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Little Italy"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Murray Hill"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Nolita"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Stuyvesant Town"] <- "Gramercy Park -  Murray Hill"
data$Zonas_agregadas[data$neighbourhood == "Flatiron District"] <- "Gramercy Park -  Murray Hill"



#8
data$Zonas_agregadas[data$neighbourhood == "Greenwich Village"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "SoHo"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "West Village"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "Chinatown"] <- "Greenwich Village - Soho"
data$Zonas_agregadas[data$neighbourhood == "Civic Center"] <- "Greenwich Village - Soho"



#9
data$Zonas_agregadas[data$neighbourhood == "Lower East Side"] <- "Union Square - Lower East Side"
data$Zonas_agregadas[data$neighbourhood == "East Village"] <- "Union Square - Lower East Side"


#10
data$Zonas_agregadas[data$neighbourhood == "Tribeca"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Two Bridges"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Financial District"] <- "Lower Manhattan"
data$Zonas_agregadas[data$neighbourhood == "Battery Park City"] <- "Lower Manhattan"



data$latitude <- as.numeric(as.character(data$latitude))

data$longitude <- as.numeric(as.character(data$longitude))

data$price <- as.numeric(data$price)

data$room_type <- factor(data$room_type)




```



```{r echo = FALSE}
ggplot(data=data, aes(x=neighbourhood)) + geom_bar(stat="count") + coord_flip()
```



```{r echo = FALSE}
  ggplot(data = data, aes(x = neighbourhood, fill=room_type)) +
  geom_bar(stat = "count", position = "dodge")+
  coord_flip()
```



```{r echo = FALSE}
  ggplot(data = data, aes(x =Zonas_agregadas, fill=room_type)) +
  geom_bar(stat = "count", position = "dodge")+
  coord_flip()

```


```{r echo=FALSE}
map <- leaflet(data) %>% addCircles()
map
```

```{r}
sites_lugares <- data.frame(longitude = c(-73.9653551, -73.9856644, -73.985131, -73.994877, -73.963244, -74.0048911708541, -73.9774991821081, -74.0151217), latitude = c(40.7828647, 40.7484405, 40.758895, 40.704345, 40.7794366, 40.74770385, 40.7616124,40.711732), Lugares = c("Central Park", "Empire State", "Times square", "Puente de Brooklyn", "Museo Metropolitano de Arte", "High Line", "MoMa Museum","One World Trade Center"))


map <- leaflet(data) %>% addCircles(color = ~id) %>% addProviderTiles(providers$MtbMap) %>% addProviderTiles(providers$Stamen.TonerLines, options = providerTileOptions(opacity = 0.35)) %>% addProviderTiles(providers$Stamen.TonerLabels) %>% addCircleMarkers(data = sites_lugares, lat = ~latitude, lng = ~longitude, color = "red", radius = 0.5)
map
```



```{r echo=FALSE}
ggplot(data, aes(x=price)) + geom_histogram(bins = 100)

```


```{r echo=FALSE}

ggplot(data, mapping=(aes(x=price, fill=room_type))) + geom_histogram(bins = 30, alpha= 0.9)

```




```{r}
g<-ggplot(data ,aes(x=Zonas_agregadas, y=price,fill=Zonas_agregadas)) +
    geom_boxplot(alpha=0.3) + scale_fill_brewer(palette = "Reds")+ coord_flip()+
    theme(legend.position="none")+ylab("Precio")+xlab("Zonas de Manhattan")+ ggtitle("Distribución del precio en función de la zona")
g
```



```{r echo=FALSE}
dg <- data %>% group_by(Zonas_agregadas) %>% summarise(media = mean(as.numeric(as.character(price)), na.rm = TRUE))

dg_or <- within(dg,Zonas_agregadas <- factor(Zonas_agregadas, levels = names(sort(table(Zonas_agregadas),
                                                                          decreasing = TRUE)))) 


precio = ggplot(dg_or, aes(x=Zonas_agregadas, y=media)) + 
  geom_bar(stat = "identity")+ coord_flip() 

precio
```



```{r}
precio = ggplot(dg_or, aes(x=reorder(Zonas_agregadas, media), y=media)) + 
  geom_bar(stat = "identity")+ coord_flip() 

precio
```




```{r include = FALSE, warning=FALSE}
d_barras <- within(data, 
               Zonas_agregadas <- factor(Zonas_agregadas, levels = names(sort(table(Zonas_agregadas),
                                                                          decreasing = TRUE))))

 

barras = d_barras %>% group_by(room_type) %>%
  count(Zonas_agregadas) %>%
  ggplot(aes(x = reorder(Zonas_agregadas, n), y = n, fill = room_type)) + coord_flip() + 
  geom_bar(stat = 'identity', position=position_dodge()) + 
  scale_fill_manual("Tipo de alojamiento", labels = c("Piso","Habitación privada") , values  = c('#FA8072', 'gray')) + ylab("Alojamientos") + theme(axis.title.y=element_blank(), axis.ticks.y=element_blank()) + theme(legend.position = "top")

barras
```


```{r echo = FALSE, warning=FALSE}
sites_lugares <- data.frame(longitude = c(-73.9653551, -73.9856644, -73.985131, -73.994877, -73.963244, -74.0048911708541, -73.9774991821081, -74.0151217), latitude = c(40.7828647, 40.7484405, 40.758895, 40.704345, 40.7794366, 40.74770385, 40.7616124,40.711732), Lugares = c("Central Park", "Empire State", "Times square", "Puente de Brooklyn", "Museo Metropolitano de Arte", "High Line", "MoMa Museum","One World Trade Center"))

beatCol <- colorNumeric(palette = '#FA8072', data$id)

map <- leaflet(data) %>% addProviderTiles(providers$CartoDB.Positron) %>% addProviderTiles(providers$Stamen.TonerLines, options = providerTileOptions(opacity = 0.35)) %>% addProviderTiles(providers$Stamen.TonerLabels) %>% addCircles(color = ~beatCol(id), weight = 0.1) %>% addCircleMarkers(data = sites_lugares, lat = ~latitude, lng = ~longitude, color = "black", radius = 0.5) 
map
```




```{r echo=FALSE, warning=FALSE}

histo1 <- plot_ly(data, alpha = 0.9, x = ~price, type = "histogram", color = ~room_type, colors =  c('#FA8072','#9b9b9b')) %>% style(hoverinfo = 'none')


histo1

```



```{r echo=FALSE, warning=FALSE}
dg <- data %>% group_by(Zonas_agregadas) %>% summarise(media = mean(as.numeric(as.character(price)), na.rm = TRUE))

dg_or <- within(dg,Zonas_agregadas <- factor(Zonas_agregadas, levels = names(sort(table(Zonas_agregadas),
                                                                          decreasing = TRUE)))) 


precio = ggplot(dg_or, aes(x=reorder(Zonas_agregadas, media), y=media, fill = '#FA8072')) + 
  geom_bar(stat = "identity", show.legend = FALSE) + ylab("Precio medio") +  theme(axis.title.y=element_blank(), axis.ticks.y=element_blank())+ coord_flip() 
precio

```



```{r echo=FALSE}
precio = ggplot(dg_or, aes(x=reorder(Zonas_agregadas, media), y=media, fill = '#FA8072')) + 
  geom_bar(stat = "identity", show.legend = FALSE) + ylab("Precio medio") + geom_text(aes(label = round(media, 2)), color = "white", position = position_stack(vjust=0.9), size = 4) +  theme(axis.title.y=element_blank(), axis.ticks.y=element_blank())+ coord_flip() 
precio

```






```{r setup, echo = FALSE, warning=FALSE, results = 'asis'}

d <- highlight_key(data)

seleccion <- bscols(filter_checkbox("room_type","Tipo de alojamiento",d,~room_type),
                    filter_select("Zonas_agregadas","Barrios",d,~Zonas_agregadas, allLevels = TRUE))


```


```{r echo=FALSE}
map <- leaflet(d) %>% addProviderTiles(providers$CartoDB.Positron) %>% addProviderTiles(providers$Stamen.TonerLines, options = providerTileOptions(opacity = 0.35)) %>% addProviderTiles(providers$Stamen.TonerLabels) %>% addCircles(color = ~beatCol(id), weight = 0.1, popup = data$Zonas_agregadas) %>% addCircleMarkers(data = sites_lugares, lat = ~latitude, lng = ~longitude, popup = ~Lugares, color = "black", radius = 0.5) %>% highlight("plotly_selected")
```

```{r echo=FALSE}
histo1 <- plot_ly(d, alpha = 0.9, x = ~price, type = "histogram", color = ~room_type, colors =  c('#FA8072','#9b9b9b'), text = ~Zonas_agregadas, hoverinfo = 'text, y') 
histo1

bscols(widths = c(12, 6, 6),histo1, map,seleccion)

```




```{r echo=FALSE}
precio_d = ggplotly(precio, tooltip = "None") %>% layout(showlegend= FALSE)
precio_d
```



```{r echo = FALSE}
inter_barras = ggplotly(barras, tooltip = "n") %>%
layout(legend = list(orientation = "h", x = 0.2, y =1.1))
inter_barras
```



```{r echo = FALSE, warning=FALSE}

bscols(widths = c(2,4,6,6,6), seleccion, map, histo1, inter_barras, precio_d)
```

